### ISSUE TITLE
Rename default label Videomail to Video Message

### ISSUE THREAD

**Issue by binarykitchen** [kjohnson/ninja-forms-videomail#15]
Tried that according to @kjohnson s comment

> If you want to edit the field configuration, that is in `ninja-forms-videomail/includes/Fields/Videomail.php`. Look in the `__construct()` method where `$this->label` is defined.
> 
> Note that it is also translated and must be inside of the `__()` method for WordPress to translate.

But I am still unsure. Had a look at that constructor

```php
class NF_Videomail_Fields_Videomail extends NF_Abstracts_Field
{
    protected $_name = 'videomail';

    protected $_section = 'common';

    protected $_type = 'videomail';

    protected $_icon = 'video-camera';

    protected $_templates = 'videomail';

    protected $_settings = array( 'label', 'label_pos', 'required', 'key' );

    public function __construct()
    {
        parent::__construct();

        $this->_nicename = __( 'Videomail', 'ninja-forms' );

        $settings = NF_Videomail::config( 'VideomailFieldSettings' );
        $this->_settings = array_merge( $this->_settings, $settings );

        add_action( 'wp_enqueue_scripts', array( $this, 'enqueue_scripts' ) );

        add_filter( 'ninja_forms_custom_columns', array( $this, 'custom_columns' ), 10, 2 );
    }
```

But still don't see where exactly to rename it?

**Comment by kjohnson** [comment]
Ah, `nicename`, not label.

```
$this->_nicename = __( 'Videomail', 'ninja-forms' );
```

**Comment by binarykitchen** [comment]
Hmmm, when I change that to `$this->_nicename = __( 'Video Message', 'ninja-forms' );`, I do not see the change on screen when editing.

**Comment by binarykitchen** [comment]
@kjohnson maybe you can try it yourself?
