### ISSUE TITLE
Define selectors for form and submit button

### ISSUE THREAD

**Issue by binarykitchen** [kjohnson/ninja-forms-videomail#16]
Ok, the new videomail-client version 1.14.0 now should embrace an existing form and submit button without automatically creating one.

See example at https://github.com/binarykitchen/videomail-client/blob/master/examples/contact_form.html#L58

Can you help me with this one and pass on these two options `formId` and `submitButtonId` to the videomail-client? Not sure how to do this.

Thanks!

**Comment by binarykitchen** [comment]
ps: `git pull` before you start ...

**Comment by kjohnson** [comment]
Yeah, can do.

**Comment by binarykitchen** [comment]
@kjohnson if you are too busy, can you give  some pointers where in the code to look at and i ll give this one a try ... thx

**Comment by kjohnson** [comment]
@binarykitchen something that I forgot about, Ninja Forms doesn't actally use a form element, since we don't actually use form submission (but rather send via AJAX).

**Comment by kjohnson** [comment]
This is something that we will probably change, thought.

**Comment by kjohnson** [comment]
Submit: `.nf-field-container.submit-container input.ninja-forms-field`

**Comment by binarykitchen** [comment]
@kjohnson well that's a CSS selector but I need an unique ID (which is also more reliable in case if we want to support multiple instances one day)

Tried something like this

```
    getSubmitButtonId: function(formId) {
        return document.getElementById('form-' + formId)
                       .querySelector("[type='submit']")
                       .getAttribute('id')
    },
```
But that doesn't work because Backbone/Marionette hasn't laid out the form element yet.

Any clues?

**Comment by kjohnson** [comment]
Using the formID, you can request the form, then loop through the fields checking for a submit button.

```js
var form = Backbone/Radio.channel( 'app' ).request( 'get:form', formID );
var submit = _.findWhere( form.get( 'fields' ), { type: submit } );
var submitID =  submit.get( 'id' );
```

Something like that.

**Comment by binarykitchen** [comment]
thx, will try that soon

**Comment by binarykitchen** [comment]
@kjohnson tried to place that in `register()` but

```
var form = Backbone.Radio.channel('app').request('get:form', fieldModel.get('formID'));
```

gives me `undefined`. There is no `<form>` element in the HTML at all. Am I doing something wrong?

**Comment by kjohnson** [comment]
Hm, that should work. I'll have to take a look this afternoon.

**Comment by binarykitchen** [comment]
@kjohnson any luck?

**Comment by kjohnson** [comment]
Ok, so if you request the form inside of the `adjustFormDataBeforePosting` callback then it will work. The field's `register` method is called before the form is actually ready (since the field is initialized as a part of initializing the form).

**Comment by binarykitchen** [comment]
@kjohnson i am afraid we do not talk about the same problem. i think you were referring to the issue #24 

but this issue #16 here is about this one problem:
https://github.com/kjohnson/ninja-forms-videomail/blob/master/assets/js/videomail.js#L62

how can i know the ID of the submit button at this line of code? it is important ...

**Comment by kjohnson** [comment]
Is it possible to listen for an event, as opposed to manually registering a listener? The Ninja Forms application already provides submission events using Backbone.Radio.

I'm not really sure how to extract a rendered element ID from the corresponding field model in the MV* pattern.

**Comment by binarykitchen** [comment]
@kjohnson really would like to know how to get the submit button ID in the MV* pattern. will try to find this out myself but tell me, where would you start? by studying the marionette or backbone api - which one?

**Comment by binarykitchen** [comment]
@kjohnson also using events won't work due to the async nature. the ninja forms application does not provide callbacks in submission events. submitting videomail data to the videomail server takes few seconds ...

**Comment by binarykitchen** [comment]
@kjohnson never mind, i found a way to get the submit button id by using `Backbone.Radio.channel('submit')` ... will push a fix soon

**Comment by binarykitchen** [comment]
done, works - but now have to fix the submit action. will do this later in a separate commit.
