### ISSUE TITLE
Field Settings

### ISSUE THREAD

**Issue by kjohnson** [kjohnson/ninja-forms-videomail#2]
Add field setting to mirror the `videomail-client` options.

Primary Settings
- [ ] Site Name (`site-name`) (REQUIRED)

Restriction Settings
- [x] Limit Seconds (`limitSeconds`)

Display Settings
- [x] Video Width (`width`)
- [x] Show Countdown (`countdown`)

Advanced Settings
- [x] Debug Mode (`verbose`)

**Comment by binarykitchen** [comment]
I would also add another option called `site-name`. Because I maintain a whitelist on the server based on this. here an example what a whitelist on the videomail server looks like for the site named `videomail-client-demo`:

```json
    "videomail-client-demo": {
        "origins": [
            "http://local.videomail-client.io:8080",
            "https://local.videomail-client.io:8080",
            "http://localhost",
            "http://localhost:8080",
            "https://localhost",
            "https://localhost:8080",
            "http://127.0.0.1",
            "http://127.0.0.1:8080",
            "https://127.0.0.1",
            "https://127.0.0.1:8080",
            "http://127.0.0.1:3000",
            "https://127.0.0.1:3000",
            "https://fiddle.jshell.net"
        ],
        "video": {
            "expireSeconds": 5184000
        },
        "audio": {
            "enabled": true
        },
        "structure": {
            "title":              "subject",
            "optionalAttributes": ["subject", "from", "body"]
        }
    }
```

If a request is made from a site with a non-existing site name, then nothing happens (think 401 is returned). Also, when a request is made from an existing site name but comes from a different URL, a 401 is returned as well. Hope this explains? Hence site-name must be configurable on Wordpress.

**Comment by kjohnson** [comment]
`site-name` added to the list.

**Comment by kjohnson** [comment]
@binarykitchen Where do I add the `site-name` option when initializing the `videomail-client`?

**Comment by kjohnson** [comment]
<img width="1280" alt="screenshot 2016-06-10 22 28 15" src="https://cloud.githubusercontent.com/assets/10858303/15982644/b45f3a9a-2f5a-11e6-955b-1f135db5ffd6.png">

**Comment by kjohnson** [comment]
@binarykitchen where can I add the `site-name` when initializing the `videomail-client`?

**Comment by binarykitchen** [comment]
Here a list of all available options with their defaults:
https://github.com/binarykitchen/videomail-client/blob/master/src/options.js#L7

Use `siteName` ;)

But feel free to add more options you think could be useful, i.E. `enablePause`, `fps` for videos (helps with performance issues) and so on.

PS: screenshot looks awesome!
