### ISSUE TITLE
Serve assets non-minified for local development

### ISSUE THREAD

**Issue by binarykitchen** [kjohnson/ninja-forms-videomail#20]
@kjohnson Do you know a trick how to serve unminified assets for local development only? This for easier debugging etc.

```
    public function enqueue_scripts()
    {
        wp_enqueue_style(
            'nf-videomail',
            NF_Videomail::$url . '/assets/css/min/videomail.min.css'
        );

        wp_enqueue_script(
            'nf-videomail-client',
            NF_Videomail::$url . '/node_modules/videomail-client/dist/videomail-client.min.js',
            false
        );

        wp_enqueue_script(
            'nf-videomail',
            NF_Videomail::$url . '/assets/js/min/videomail.min.js',
            array('nf-front-end', 'nf-videomail-client')
        );
    }
```

Any tricks how to adjust the above code? Is there a hidden WordPress flag somewhere we can use?

**Comment by kjohnson** [comment]
I usually set an `NF_DEV` flag for Ninja Forms development, which I could check against to adjust the source.

**Comment by kjohnson** [comment]
@binarykitchen Similar to [WP_DEBUG](https://codex.wordpress.org/WP_DEBUG) you can set the `NF_DEV` definition in the `wp-config.php` file.

**Comment by binarykitchen** [comment]
great many thanks

**Comment by binarykitchen** [comment]
@kjohnson is there a wordpress plugin i can use to set `NF_DEV` in the wp-config.php instead of editing the file itself? would be a bit cumbersome with the bitnami wordpress stack or am i wrong here?

**Comment by kjohnson** [comment]
It does need to be set manually, there is not a plugin option. The `wp-config.php

**Comment by binarykitchen** [comment]
Right. Just did that. All good. Thanks
