### ISSUE TITLE
Set from/to/subject/text before posting videomail

### ISSUE THREAD

**Issue by binarykitchen** [kjohnson/ninja-forms-videomail#24]
Need to figure out how we can retrieve those form values before posting the videomail to the videomail server. The come from a config, can look like `{field:email_2}` and the question is how to get its real form value?

See https://github.com/kjohnson/ninja-forms-videomail/blob/master/assets/js/videomail.js#L31 for detailed problem description

**Comment by kjohnson** [comment]
Inside of the `adjustFormDataBeforePosting ` method you can get the field values using:

```js
var emailFromFieldName = getFieldValueByKey( '{field:email_2}', formID );

function getFieldValueByKey( key, formID ) { // Field Keys are unique to a form.

    // Extract the key from the merge tag.
    key = key.replace( '{field:', '').replace( '}', '' );

    // Get the field by Key
    var field = Backbone.Radio.channel( 'form-' + formID ).request( 'get:fieldByKey', key );

    return field.get( 'value' );
}
```

**Comment by binarykitchen** [comment]
that worked, thanks
