### ISSUE TITLE
Video Preview Thumbnail

### ISSUE THREAD

**Issue by kjohnson** [kjohnson/ninja-forms-videomail#4]
Not sure if this is supported by videomail, but grabbing a preview thumbnail of the video could be useful as a merge tag value. Could be used to display in an email, etc.

**Comment by binarykitchen** [comment]
yes, an url for the preview thumbnail should be already in the POST response. if not, then i can fix this. let me know

**Comment by kjohnson** [comment]
Found it: `poster`
