### ISSUE TITLE
Support required field setting

### ISSUE THREAD

**Issue by kjohnson** [kjohnson/ninja-forms-videomail#8]
To make the `videomail` field required, we will need some custom JS to disable/enable the submit button.

**Comment by binarykitchen** [comment]
good point - i ll think about it and will probably add a new api call. probably in a couple of days.

**Comment by kjohnson** [comment]
@binarykitchen I'm looking at this from a Ninja Forms perspective, which natively supports required validation when using simple string values. The videomail field will need a custom handler.

**Comment by binarykitchen** [comment]
Understand + agree. Will think of something this week and come back to you.

**Comment by binarykitchen** [comment]
In the middle of it. Found something else, the option `enableAutoValidation` should probably be set to `false` for this plugin, this to deactivate too many validation events (not related to this issue but a good performance tuning I guess)

**Comment by binarykitchen** [comment]
done, new version of videomail-client 1.13.1 is out and has a new api function `setSubmitButtonAttribute`, see:
https://github.com/binarykitchen/videomail-client#setSubmitButtonAttribute
